$:.unshift(File.dirname(__FILE__) + '/../lib')
require 'callbacks'

class Tester

  def boot
    return "booting"
  end

  def exit
    return "exiting"
  end

  def testing
    return "testing"
  end
  
  def before_callback_with_defined_method
    text = "This is before the method ran and is generated by a defined method in the class"
    $tests_run << text
    return text
  end
  
  def callback_with_defined_method
  end
  
  def fill_globalvar_tests_run
    $tests_run << 'fill_globalvar_tests_run'
  end

  include Callbacks
end