# $Id$

load 'tasks/setup.rb'

task :default => :build

desc 'deploy the site to the webserver'
task :deploy => [:build, 'deploy:rsync']

SITE.base = 'http://callbacks.rubyforge.org'
SITE.host = 'rubyforge.org'
SITE.user = 'leonb'
SITE.remote_dir = '/var/www/gforge-projects/callbacks'
SITE.exclude = %w(docs)

# EOF
